import { PageHeader } from "@/components/common/page-header";
import { GlassCard } from "@/components/common/glass-card";
import { Download, FileCode, Search } from "lucide-react";

export default function FilesPage() {
  return (
    <div className="max-w-6xl mx-auto">
      <PageHeader 
        title="Generated Files" 
        description="Access and download files generated by the AI agent"
      />
      
      <GlassCard className="p-0 overflow-hidden">
        <div className="p-4 border-b border-white/5 flex items-center justify-between">
          <h3 className="text-sm font-medium text-white">Workspace Files</h3>
          <div className="relative">
            <Search className="w-4 h-4 text-gray-400 absolute left-3 top-1/2 -translate-y-1/2" />
            <input 
              type="text" 
              placeholder="Filter files..." 
              className="bg-surface/50 border border-white/10 rounded-lg pl-9 pr-3 py-1.5 text-sm text-white focus:outline-none focus:border-accent/50 w-64"
            />
          </div>
        </div>
        
        <div className="p-4 grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
          {[1, 2, 3, 4, 5, 6].map((i) => (
            <div key={i} className="p-4 rounded-xl border border-white/5 bg-surface/30 hover:bg-surface/50 transition-colors flex flex-col gap-4 group">
              <div className="flex items-start justify-between">
                <div className="w-10 h-10 rounded-lg bg-accent/10 flex items-center justify-center">
                  <FileCode className="w-5 h-5 text-accent" />
                </div>
                <button className="w-8 h-8 rounded-lg flex items-center justify-center text-gray-400 hover:text-white hover:bg-white/10 opacity-0 group-hover:opacity-100 transition-all">
                  <Download className="w-4 h-4" />
                </button>
              </div>
              <div>
                <p className="text-sm font-medium text-white truncate">data_processor_script_{i}.py</p>
                <p className="text-xs text-gray-500 mt-1">Generated today at 14:2{i}</p>
              </div>
            </div>
          ))}
        </div>
      </GlassCard>
    </div>
  );
}
